sudo: required

services:
  - docker

before_install:
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"

script:
  # build-essential is just a base Ubuntu Trusty image with an updated apt-cache and essential compilation tools
  # - make -C build-essential install push
  # build-java adds JDK 8 and Maven 3.3 to build-essential for building Java-based apps
  # - make -C build-java install push
  # build-scala adds SBT to the build-java image for building Scala-based apps
  # - make -C build-scala install push
  # trusty-minimal is just Ubuntu with an updated apt-cache in order to make round trips of installing faster
  # - make -C trusty-minimal install push
  # artifactory is an Artifactory 4 OSS install that is based on Ubuntu rather than CentOS as the official one is
  # - make -C artifactory install push
  # zeppelin is an Apache Zeppelin install
  # - make -C zeppelin install push
  # erlang-kerl is an image meant to build Erlang-based applications that require kerl
  - travis_wait make -C erlang-kerl install push
