TAG              := jbrisbin/artifactory-oss
MAINTAINER       := Jon Brisbin <jon@jbrisbin.com>
FROM             := jbrisbin/build-java:8
ENTRYPOINT       := bin/artifactory.sh

OVERLAYS         := artifactory-oss

include ../docker.mk
