TAG               := jbrisbin/zeppelin

FROM              := jbrisbin/alpine-java
MAINTAINER        := Jon Brisbin <jon@jbrisbin.com>

OVERLAYS          := env packages zeppelin

include ../docker.mk
